version: '3'

services:
  web:
    build: Dockerfile.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./app:/home/chift_technical_test/app
    ports:
      - 80:80
    depends_on:
      - postgres
    # allow docker container to connect to local odoo instance for development
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chift_technical_test
    expose:
      - 5432

volumes:
  postgres_data: